package com.pm.patientservice.mapper;

import com.pm.patientservice.dto.PatientRequestDTO;
import com.pm.patientservice.dto.PatientResponseDTO;
import com.pm.patientservice.model.Patient;
import java.util.List;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Entity &lt;-&gt; DTO mapping for patients. MapStruct generates the implementation at compile
 * time (no reflection) and registers it as a Spring bean (componentModel=spring, set globally
 * in the pom). Adding an unmapped target field fails the build (unmappedTargetPolicy=ERROR).
 */
@Mapper
public interface PatientMapper {

    PatientResponseDTO toResponse(Patient patient);

    List<PatientResponseDTO> toResponses(List<Patient> patients);

    /**
     * Builds a new entity from a create request. {@code id} is generated by JPA and
     * {@code registeredDate} is set by the service, so both are ignored here.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "registeredDate", ignore = true)
    Patient toEntity(PatientRequestDTO request);
}
